import { useEffect,useState } from 'react'
import { supabase } from '../lib/supabaseClient'
import { useSettings } from '../lib/SettingsContext'
import { formatCurrency,formatPercent } from '../lib/format'
import KpiCard from '../components/KpiCard'
import DataTable,{Column} from '../components/DataTable'
import { Wallet,Receipt,PiggyBank,Percent } from 'lucide-react'
interface BudgetRow{category_id:string;category_name:string;category_type:'income'|'expense';planned_amount:number;actual_amount:number}
type Status='On Track'|'Near Limit'|'Over Budget'
function computeStatus(p:number):Status{if(p>1)return'Over Budget';if(p>=.81)return'Near Limit';return'On Track'}
const statusTone:Record<Status,string>={'On Track':'bg-positive-bg text-positive','Near Limit':'bg-warning-bg text-warning','Over Budget':'bg-negative-bg text-negative'}
export default function MonthlyBudget(){const{settings}=useSettings();const[rows,setRows]=useState<BudgetRow[]>([]);async function load(){const{data}=await supabase.from('v_budget_status').select('*').eq('month',settings.month).eq('year',settings.year);setRows(data??[])}useEffect(()=>{load()},[settings.month,settings.year]);const incomeRows=rows.filter(r=>r.category_type==='income'),expenseRows=rows.filter(r=>r.category_type==='expense');const plannedIncome=incomeRows.reduce((s,r)=>s+r.planned_amount,0),actualIncome=incomeRows.reduce((s,r)=>s+r.actual_amount,0),plannedExpenses=expenseRows.reduce((s,r)=>s+r.planned_amount,0),actualExpenses=expenseRows.reduce((s,r)=>s+r.actual_amount,0);const plannedSavings=plannedIncome-plannedExpenses,actualSavings=actualIncome-actualExpenses,remainingBudget=plannedExpenses-actualExpenses,savingsRate=actualIncome>0?actualSavings/actualIncome:0;const columns:Column<BudgetRow>[]=[{header:'Category',accessor:r=>r.category_name},{header:'Planned Amount',accessor:r=>formatCurrency(r.planned_amount,settings.currency),align:'right'},{header:'Actual Amount',accessor:r=>formatCurrency(r.actual_amount,settings.currency),align:'right',computed:true},{header:'Difference',accessor:r=>{const d=r.planned_amount-r.actual_amount;return <span className={d<0?'text-negative':d>0?'text-positive':'text-slate-500'}>{formatCurrency(d,settings.currency)}</span>},align:'right',computed:true},{header:'% Used',accessor:r=>formatPercent(r.planned_amount>0?r.actual_amount/r.planned_amount:0),align:'right',computed:true},{header:'Status',accessor:r=>{const p=r.planned_amount>0?r.actual_amount/r.planned_amount:0,s=computeStatus(p);return <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${statusTone[s]}`}>{s}</span>},computed:true}];return <div className="space-y-6"><div className="grid grid-cols-4 gap-3"><KpiCard label="Planned Income" value={formatCurrency(plannedIncome,settings.currency)} icon={Wallet} tone="info"/><KpiCard label="Actual Income" value={formatCurrency(actualIncome,settings.currency)} icon={Wallet} tone="info"/><KpiCard label="Planned Expenses" value={formatCurrency(plannedExpenses,settings.currency)} icon={Receipt} tone="warning"/><KpiCard label="Actual Expenses" value={formatCurrency(actualExpenses,settings.currency)} icon={Receipt} tone="negative"/><KpiCard label="Planned Savings" value={formatCurrency(plannedSavings,settings.currency)} icon={PiggyBank} tone="positive"/><KpiCard label="Actual Savings" value={formatCurrency(actualSavings,settings.currency)} icon={PiggyBank} tone="positive"/><KpiCard label="Remaining Budget" value={formatCurrency(remainingBudget,settings.currency)} icon={Receipt} tone={remainingBudget<0?'negative':'positive'}/><KpiCard label="Savings Rate" value={formatPercent(savingsRate)} icon={Percent} tone="analytic"/></div><DataTable columns={columns} rows={rows} emptyLabel="No planned amounts set yet — add categories and planned amounts to begin."/></div>}